version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "KoalbyMQP"
    assignees:
      - "KoalbyMQP"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"

  # Docker dependencies in Dockerfiles
  - package-ecosystem: "docker"
    directory: "/infra/containers/builder"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "KoalbyMQP"
    assignees:
      - "KoalbyMQP"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "builder"

  - package-ecosystem: "docker"
    directory: "/infra/containers/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "KoalbyMQP"
    assignees:
      - "KoalbyMQP"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "dev"

  # Git submodules (if needed for buildroot updates)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "KoalbyMQP"
    assignees:
      - "KoalbyMQP"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "submodules"
      - "manual-review"
