# FIXME: For github actions we will need a lot simpler of a settup (maybe caching)

FROM nixos/nix:latest

RUN nix-env -iA nixpkgs.bashInteractive nixpkgs.git

RUN mkdir -p /etc/nix && \
    echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf

# Add FHS compatibility for buildroot
RUN mkdir -p /bin /usr/bin && \
    nix-env -iA nixpkgs.file nixpkgs.perl nixpkgs.coreutils && \
    ln -sf /root/.nix-profile/bin/file /usr/bin/file && \
    ln -sf /root/.nix-profile/bin/perl /usr/bin/perl && \
    ln -sf /root/.nix-profile/bin/true /bin/true && \
    ln -sf /root/.nix-profile/bin/false /bin/false && \
    ln -sf /root/.nix-profile/bin/sh /bin/sh

WORKDIR /workspace

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["build"]