name: Enable Auto-merge for Dependabot

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number || context.payload.pull_request.number
            });

            console.log(`Processing PR #${pr.number}: ${pr.title}`);

            // Check if this is an eligible update
            const autoMergeLabels = ['auto-merge', 'github-actions', 'docker'];
            const manualReviewLabels = ['manual-review', 'submodules'];

            const hasAutoMergeLabel = pr.labels.some(label =>
              autoMergeLabels.includes(label.name)
            );

            const hasManualReviewLabel = pr.labels.some(label =>
              manualReviewLabels.includes(label.name)
            );

            if (hasManualReviewLabel) {
              console.log('Manual review required - not enabling auto-merge');
              return;
            }

            if (hasAutoMergeLabel) {
              console.log('Enabling auto-merge for eligible Dependabot PR');

              try {
                // Enable auto-merge
                await github.rest.pulls.updatePullRequest({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  auto_merge: {
                    merge_method: 'squash'
                  }
                });

                console.log('Auto-merge enabled successfully');

              } catch (error) {
                console.log('Failed to enable auto-merge:', error.message);
              }
            } else {
              console.log('PR not eligible for auto-merge (missing required labels)');
            }
